### ISSUE TITLE
이런 멀록같은.

### ISSUE THREAD

**Issue by marioman0** [Friendly-Murloc/Example#2]
@Nopied 뭘 열어야되는지 까먹음 ^~^

**Comment by Nopied** [comment]
@marioman0 뭘 까먹은건데?

**Comment by marioman0** [comment]
초기화면 c#여는거 
지금 버튼 개인적으로 버튼짜보고 있는대 particl class로 분활해볼깨

**Comment by Nopied** [comment]
@marioman0 프로젝트 열면 다 될텐데...?

**Comment by marioman0** [comment]
Example/WindowsFormsApplication1/WindowsFormsApplication1/Program.cs 이건가

**Comment by Nopied** [comment]
@marioman0 노노 그냥 보면 버추얼 스튜디오 프로젝트 파일 있어. 거기를 봐.

**Comment by marioman0** [comment]
내가 못찾는건가 왜자꾸 열면 패킷같은게 뜨지

**Comment by Nopied** [comment]
@marioman0 그럼 알아서 작성해봐 ㅇㅇ..
